import OracleDB from "oracledb";
import "dotenv/config"

OracleDB.initOracleClient({ libDir: 'C:/oracle/instantclient_21_7' });
const pool = await OracleDB.createPool({ user: "admin", password: process.env.ORACLE_DB_PASSWORD, connectionString: "GOALSDB_high", cloud: true });

export async function execute(query, values) {
    const connection = await pool.getConnection();

    try {
        const result = await connection.execute(query, values);
        await connection.commit();
        await connection.close();
        return result;
    } catch (error) {
        console.log(error)
        throw new Error(error);
    }
}

export const usersTable = "users";
export const goalsTable = "goals";

export async function createUsersTable() {
    const createUsersTable = `
    CREATE TABLE ${usersTable}(
        id NUMBER GENERATED by default on null as IDENTITY,
        name VARCHAR(30) NOT NULL,
        email VARCHAR(255) NOT NULL UNIQUE,
        password VARCHAR(255) NOT NULL,
        email_verified NUMBER(1) default on null 0
        )
    `

    execute(createUsersTable);
}


export async function createGoalsTable() {
    const createGoalsTable = `
    CREATE TABLE goals(
        id NUMBER GENERATED by default on null as IDENTITY,
        title VARCHAR(30),
        description VARCHAR(255),
        due_date DATE,
        value NUMBER,
        current_value NUMBER,
        user_id NUMBER(10)
        )
    `

    execute(createGoalsTable);
}
