import OracleDB from "oracledb";
OracleDB.initOracleClient({ libDir: 'C:/oracle/instantclient_21_7' });

export async function execute(query) {
    const db = await OracleDB.getConnection({ user: "admin", password: process.env.ORACLE_DB_PASSWORD, connectionString: "GOALSDB_high" });
    const result = await db.execute(query);
    db.commit();
    db.close();

    return result;
}

export const usersTable = "users";
export const goalsTable = "goals";

export const createUsersTable = `
CREATE TABLE ${usersTable}(
    id NUMBER GENERATED by default on null as IDENTITY,
    name VARCHAR(30) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email_verified NUMBER(1) default on null 0
    )
`

export const createGoalsTable = `
CREATE TABLE goals(
    id NUMBER GENERATED by default on null as IDENTITY,
    title VARCHAR(30),
    description VARCHAR(255),
    due_date DATE,
    value NUMBER,
    current_value NUMBER
    )
`