import OracleDB from "oracledb";
OracleDB.initOracleClient({ libDir: 'C:/oracle/instantclient_21_7' });

async function execute(query) {
    const db = await OracleDB.getConnection({ user: "admin", password: process.env.ORACLE_DB_PASSWORD, connectionString: "GOALSDB_high" });
    console.log(query)
    const result = await db.execute(query);
    db.commit();
    db.close();
    return result;
}

const usersTable = "users";
const goalsTable = "goals";

export async function loginUserService({ email, password }) {
    await execute(`CREATE TABLE ${usersTable}(id NUMBER GENERATED by default on null as IDENTITY,name VARCHAR(30) NOT NULL,email VARCHAR(255) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,email_verified NUMBER(1) default on null 0);`);

    return 0;
    try {
        console.log("executing")
        return await execute(createUsersTable)
    } catch (err) {
        console.log(err.message);
        return err.message;
    }
}


const createUsersTable = `
CREATE TABLE ${usersTable}(id NUMBER GENERATED by default on null as IDENTITY,name VARCHAR(30) NOT NULL,email VARCHAR(255) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,email_verified NUMBER(1) default on null 0);
`

const createGoalsTable = `
CREATE TABLE goals(
    id NUMBER GENERATED by default on null as IDENTITY,
    title VARCHAR(30),
    description VARCHAR(255),
    due_date DATE,
    value NUMBER,
    current_value NUMBER
    );
`